### ISSUE TITLE
expose .print() like in cliclopts

### ISSUE THREAD

**Issue by yoshuawuyts** [maxogden/subcommand#3]
I noticed [`cliclopts`](https://github.com/finnp/cliclopts) has `.print()` function, which is pretty neat (hurray for no more manual text aligning!) I was wondering what your opinions are about exposing this in `subcommand`. If it's something you like, I'd be happy to PR this. Thanks!

**Comment by joehand** [comment]
Added [usage option](https://github.com/maxogden/subcommand#usage) in `2.1.0` !
